Repository kelltom/OS-Bot-COLOR, pull requests merged in 2023-02, with the labels that each got.

#126 Potential fix for false-positive antivirus trigger
  src/utilities/settings.py
Labels: type: bug

#131 Add inventory full check for Morg API
  src/utilities/api/morg_http_client.py
Labels: type: enhancement

#130 Add Rectangle sorting key function and improve RuneLiteBot loot function
  src/model/runelite_bot.py
  src/utilities/geometry.py
  src/utilities/runelite_cv.py
Labels: type: enhancement

#108 Added OSRS Wiki Sprite Scraper
  .gitignore
  requirements.txt
  src/images/bot/scraper/.gitkeep
  src/images/ui/scraper.png
  src/utilities/sprite_scraper.py
  src/view/__init__.py
  src/view/sprite_scraper_view.py
  src/view/title_view.py
Labels: type: feature request

#135 Potential fix for OCR failure on crowded text
  src/utilities/ocr.py
Labels: type: bug

#137 Fixed Sprite Scraper bank variant algorithm
  src/utilities/sprite_scraper.py
Labels: type: bug

#140 Fix incorrect inventory slot spacing
  src/utilities/window.py
Labels: type: bug
