Repository kelltom/OS-Bot-COLOR, pull requests merged in 2023-04, with the labels that each got.

#152 Add StatusSocket methods for checking skill levels
  src/utilities/api/status_socket.py
Labels: type: enhancement

#151 Removes pag mouse calls and uses Mouse class
  src/model/bot.py
Labels: type: enhancement, status: under review

#146 Add Is Inventory Empty Method to Morg API
  src/utilities/api/morg_http_client.py
Labels: type: enhancement

#159 Improve OCR (font cropping, false positive prevention)
  src/utilities/debug.py
  src/utilities/ocr.py
Labels: type: enhancement

#157 Remastered the Sprite Scraper utility (swapped BS4 for API + improvements)
  requirements.txt
  src/utilities/sprite_scraper.py
Labels: type: feature request, type: enhancement

#147 Add MorgAPI method to get first occurrence of item(s) in inventory
  src/utilities/api/morg_http_client.py
Labels: type: feature request, type: enhancement
