Repository kelltom/OS-Bot-COLOR, pull requests merged in 2023-01, with the labels that each got.

#93 Adds rooftop plugin for training agility
  src/runelite_settings/osrs_settings.properties
Labels: status: needs information, type: enhancement

#95 Add RSN Hider to plugin list
  src/runelite_settings/near-reality_settings.properties
  src/runelite_settings/osrs_settings.properties
Labels: type: enhancement, status: confirmed

#96 Various utility improvements
  requirements.txt
  src/model/bot.py
  src/model/near_reality/pickpocket.py
  src/model/osrs/woodcutter.py
  src/utilities/api/item_ids.py
  src/utilities/api/morg_http_client.py
  src/utilities/api/status_socket.py
  src/utilities/debug.py
  src/utilities/mouse.py
  src/utilities/random_util.py
Labels: type: enhancement, status: confirmed

#99 Improve Morg API error handling
  src/model/bot.py
  src/model/runelite_bot.py
  src/utilities/api/item_ids.py
  src/utilities/api/morg_http_client.py
  src/utilities/api/status_socket.py
  src/utilities/ocr.py
Labels: type: bug, status: confirmed

#106 Remove unused function
  src/model/bot.py
Labels: type: enhancement, status: confirmed

#101 Bot control keyboard shortcut improvements
  src/view/info_frame.py
Labels: type: bug, status: needs information, type: enhancement, type: discussion

#110 Fixed type annotation flaw
  src/model/bot.py
Labels: type: bug, status: confirmed

#87 Add camera rotation function
  src/model/bot.py
Labels: type: feature request, status: needs information

#112 Reimplement detect red clicks
  src/images/bot/mouse_clicks/red_1.png
  src/images/bot/mouse_clicks/red_2.png
  src/images/bot/mouse_clicks/red_3.png
  src/images/bot/mouse_clicks/red_4.png
  src/utilities/imagesearch.py
  src/utilities/mouse.py
Labels: type: enhancement, status: confirmed

#104 API improvements for equipment
  src/model/runelite_bot.py
  src/utilities/api/morg_http_client.py
  src/utilities/api/status_socket.py
Labels: type: enhancement, status: under review

#120 Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: type: bug

#113 Add global settings page
  .gitignore
  src/OSBC.py
  src/images/ui/check.png
  src/images/ui/edit.png
  src/utilities/settings.py
  src/view/__init__.py
  src/view/info_frame.py
  src/view/settings_view.py
Labels: type: feature request

#122 Added function to get latest chat message
  src/utilities/api/morg_http_client.py
Labels: type: enhancement

#125 Fixed the Bot.stop() function from failing when called explicitly within script
  src/model/bot.py
  src/model/near_reality/combat.py
  src/model/near_reality/fishing.py
  src/model/near_reality/mining.py
  src/model/near_reality/pickpocket.py
  src/model/near_reality/woodcutting.py
  src/model/osrs/woodcutter.py
  src/model/zaros/woodcutting.py
Labels: type: bug
